name: profile
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run on each push on the master branch
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/profile@latest
        with:
          token: ${{ secrets.profile }}
          
          # Options
          user: MEDELBOU3
          template: classic
          base: ""
          config_timezone: Africa/Casablanca
          filename: profile.plugin.isocalendar.fully.featured.svg
          
          # 3D Calendar (The Blocks)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          # Languages (The Pie Chart)
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: lines, percentage
          plugin_languages_limit: 8
          
          # Activity (The Radar Chart logic)
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 14
          plugin_habits_from: 200
